name: clean_dart_cli
description: This project is one CLI for integrate Flutter and Dart with Clean Architecture
version: 0.0.30
homepage: https://github.com/sthormio/clean-dart-cli

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
 path: ^1.7.0
 args: ^1.6.0
 get_it: ^5.0.1
 ansicolor: ^1.0.2
 recase: ^3.0.0
 process_run: ^0.11.0+2

dev_dependencies:
  test: ^1.14.4

executables:
  clean-dart: clean-dart-cli
